### ISSUE TITLE
Image Not In Center of Canvas Initially

### ISSUE THREAD

**Issue by AbdullahAhmadAAK** [CaptainCodeman/svelte-pan-zoom#6]
Hi. According to the description, the package automatically places the drawn image in the center of the canvas.

I have seen the canvas' dimensions, as can be observed in the video, and it seems to be the gray area only. Or does the canvas extend downwards as well? If it is indeed the shown gray area only, then why isn't it neither horizontally nor vertically in the center?

Often, the drawn image is not within the 1st view of the canvas at all, and I have to pan down to get a glimpse of it, as can be seen in the video.

The relevant code snippets (SvelteKit) are as follows:

**Script:**

```
import { panzoom } from 'svelte-pan-zoom'

const makeCanvasOptions = (imageSource) => {
		const image = new Image()

		const options = {
			width: image.width,
			height: image.height,
			render
		}

		image.src = imageSource

		function render(ctx) {
			// const canvasWidth = ctx.canvas.width;
			// const canvasHeight = ctx.canvas.height;
			// const x = (canvasWidth - image.width) / 2;
			// const y = (canvasHeight - image.height) / 2;

			// ctx.clearRect(0, 0, canvasWidth, canvasHeight); // Clear the canvas before drawing
			// ctx.drawImage(image, x, y); // Draw image at calculated center position

			ctx.drawImage(image, 0, 0)
		}

		return options
	}
```

**HTML:**

```
{#if $showModal}
			<div
				class="fixed inset-0 bg-black bg-opacity-75 flex justify-center items-center z-50"
				on:click={closeModal}
			>
				<div
					class="relative max-w-[90%] max-h-[90%] min-h-[20%] bg-white p-4 rounded shadow-lg overflow-hidden"
					on:click|stopPropagation
				>
					{#if $selectedItem.type === 'image'}
						<canvas width="100%" height="100%" use:panzoom={makeCanvasOptions($selectedItem.src)} />
					{:else if $selectedItem.type === 'video'}
						<div class="flex flex-col h-full justify-between">
							<video controls class="max-h-full max-w-full my-auto">
								<source src={$selectedItem.src} type="video/mp4" />
							</video>
						</div>
					{/if}
					<!-- Close button in the modal -->
					<button
						class="absolute top-2 right-2 text-black bg-gray-200 rounded-full p-1"
						on:click={closeModal}
					>
						&#10005;
					</button>
				</div>
			</div>
		{/if}
```

Here is the video of the issue, and of my tinkering around in Developer Tools mode.

https://github.com/user-attachments/assets/1203602e-a64b-4e25-a854-891ab8609933

**Comment by CaptainCodeman** [comment]
The video is a bit too fast to really follow, but it looked like the canvas wasn't sized correctly and was going off the bottom of the screen, which would account for it.

It'd be better to create a REPL / playground to demonstrate your issue:
https://svelte.dev/playground/hello-world?version=5.1.16
