### ISSUE TITLE
Display Issue with Vertically Tall Video (panning limit on zoomed out state + snapping of image on zoomed in state)

### ISSUE THREAD

**Issue by AbdullahAhmadAAK** [CaptainCodeman/svelte-pan-zoom#7]
The visualization of files with large height is still a bit complicated. Mainly because I can't drag the image to the bottom end, and when I'm zoomed in, if I try to drag, the image goes back to the top:

https://drive.google.com/file/d/1RnkrUDyYXUCwBGQy3TWWpYV57C5lXARB/view?usp=sharing

This is a video of me trying to inspect the issue in Developer Tools mode:

https://github.com/user-attachments/assets/fab80960-d65e-4856-b32d-87cde134de58

This is the code I'm using.
![code](https://github.com/user-attachments/assets/78e361de-59e0-4655-9414-34709bdf63b3)

Can you please suggest a solution for this?

**Comment by CaptainCodeman** [comment]
I'd guess it's the same issue as your last one, but it's impossible to debug a video or a picture of code.

**Comment by AbdullahAhmadAAK** [comment]
Ok. I am in the process of making a playground app for this. @CaptainCodeman 

In the meantime, can you tell me anything you know about panning limits in your package? To what extent can an image be panned within the canvas? Is there some sort of limit you have?

Secondly, why is there the snappy behaviour when we pan after zooming in? Both of these are related to the panzoom package.
